export const sampleVerses: Record<string, string[]> = {
  "john-1": [
    "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "The same was in the beginning with God.",
    "All things were made by him; and without him was not any thing made that was made.",
    "In him was life; and the life was the light of men.",
    "And the light shineth in darkness; and the darkness comprehended it not.",
    "There was a man sent from God, whose name was John.",
    "The same came for a witness, to bear witness of the Light, that all men through him might believe.",
    "He was not that Light, but was sent to bear witness of that Light.",
    "That was the true Light, which lighteth every man that cometh into the world.",
    "He was in the world, and the world was made by him, and the world knew him not.",
    "He came unto his own, and his own received him not.",
    "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:",
    "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
    "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.",
    "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me.",
    "And of his fulness have all we received, and grace for grace.",
    "For the law was given by Moses, but grace and truth came by Jesus Christ.",
    "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.",
  ],
  "john-3": [
    "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
    "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
    "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
    "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
    "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit.",
    "Marvel not that I said unto thee, Ye must be born again.",
    "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
    "Nicodemus answered and said unto him, How can these things be?",
    "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?",
    "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
    "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
    "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
    "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:",
    "That whosoever believeth in him should not perish, but have eternal life.",
    "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
    "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
    "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil.",
    "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved.",
    "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God.",
  ],
  "psalms-23": [
    "The LORD is my shepherd; I shall not want.",
    "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
    "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
    "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
    "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.",
  ],
  "romans-8": [
    "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
    "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
    "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh:",
    "That the righteousness of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
    "For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit.",
    "For to be carnally minded is death; but to be spiritually minded is life and peace.",
    "Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be.",
    "So then they that are in the flesh cannot please God.",
    "But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you. Now if any man have not the Spirit of Christ, he is none of his.",
    "And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.",
    "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you.",
    "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh.",
    "For if ye live after the flesh, ye shall die: but if ye through the Spirit do mortify the deeds of the body, ye shall live.",
    "For as many as are led by the Spirit of God, they are the sons of God.",
    "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father.",
    "The Spirit itself beareth witness with our spirit, that we are the children of God:",
    "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.",
    "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
  ],
  "genesis-1": [
    "In the beginning God created the heaven and the earth.",
    "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.",
    "And God said, Let there be light: and there was light.",
    "And God saw the light, that it was good: and God divided the light from the darkness.",
    "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.",
    "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.",
    "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.",
    "And God called the firmament Heaven. And the evening and the morning were the second day.",
    "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.",
    "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.",
  ],
  "proverbs-3": [
    "My son, forget not my law; but let thine heart keep my commandments:",
    "For length of days, and long life, and peace, shall they add to thee.",
    "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:",
    "So shalt thou find favour and good understanding in the sight of God and man.",
    "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
    "In all thy ways acknowledge him, and he shall direct thy paths.",
    "Be not wise in thine own eyes: fear the LORD, and depart from evil.",
    "It shall be health to thy navel, and marrow to thy bones.",
    "Honour the LORD with thy substance, and with the firstfruits of all thine increase:",
    "So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.",
  ],
}
